# myRC - Kustomize Configuration
# License: MIT
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myrc

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app: myrc
  version: "1.0.0"

commonAnnotations:
  managed-by: "kustomize"
  documentation: "https://github.com/myrc/myrc"
