apiVersion: v1
kind: ConfigMap
metadata:
  name: myrc-config
  namespace: myrc
data:
  SPRING_PROFILES_ACTIVE: "prod"
  APP_CORS_ALLOWED_ORIGINS: "http://myrc.local,http://localhost:8000"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_MYRC: "DEBUG"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_FLYWAY_ENABLED: "true"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: "50MB"
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: "50MB"
