apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../k8s

patches:
  - path: reduce-replicas.yaml
  - path: pdb-patch.yaml
  - path: ingress-patch.yaml
  - path: configmap-patch.yaml
  - path: hpa-patch.yaml
